<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[43]=array(0,1,1,'5LiT6aKY54Ot54K5');
$cfg_Cs[44]=array(0,1,1,'5Y6G5Y+y5o6o6YCB');
$cfg_Cs[45]=array(0,1,1,'5pyN5Yqh');
$cfg_Cs[46]=array(0,1,1,'5LqS5Yqo');
$cfg_Cs[47]=array(45,1,1,'5YWs5Zut57u/5Zyw');
$cfg_Cs[48]=array(45,1,1,'5Y+k5qCR6LWE5rqQ');
$cfg_Cs[49]=array(45,1,1,'5p6X5Lia6LWE5rqQ');
$cfg_Cs[50]=array(45,1,1,'5rm/5Zyw6LWE5rqQ');
$cfg_Cs[51]=array(45,1,1,'6YeO55Sf5Yqo54mp5L+d5oqk');
$cfg_Cs[52]=array(45,1,1,'55eF6Jmr5a6z6aKE6Ziy');
$cfg_Cs[53]=array(45,1,1,'5bi46KeB5qSN54mp56eR5pmu');
$cfg_Cs[54]=array(46,1,1,'5oql5ZCN5LqS5Yqo');
$cfg_Cs[55]=array(46,1,1,'5rS75Yqo5Zue6aG+');
$cfg_Cs[56]=array(0,1,1,'5LqM57u056CB6LWE6K6v');
?>