
    <m:item name='会议信息' ischannel='1' link='content_sg_list.php?channelid=-8' linkadd='archives_sg_add.php?channelid=-8' channelid='-8' rank='' target='main' />
  <m:item name='新闻咨询' ischannel='1' link='content_list.php?channelid=1' linkadd='article_add.php?channelid=1' channelid='1' rank='' target='main' />

  <m:item name='专题管理' ischannel='1' link='content_s_list.php' linkadd='spec_add.php' channelid='-1' rank='spec_New' target='main' />
